### ISSUE TITLE
Mapchange won't start

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Reispfannenfresser/partly-adequate-mapvote#8] opened 2020-04-15 16:05 UTC
**Description**
After the last update it does not change the map and returns me this error in the server side console
![image](https://user-images.githubusercontent.com/36534723/79359722-395aa680-7f43-11ea-993f-a266c8847e79.png)

[Partly Adequate Mapvote] lua/includes/extensions/table.lua:693: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:693
    3. PrintTable - lua/includes/util.lua:63
     4. unknown - lua/pam/server/sv_pam.lua:106
 
Timer Failed! [PAM_Vote_Timer][@lua/pam/server/sv_pam.lua (line 81)]

PS: also the cvar dosen't store for my and after server restart they reset

**Comment by Reispfannenfresser** [comment] 2020-04-15 16:19
Thanks for letting me know.
I was missing a nil check. It should be fixed now.

The convars not saving is a problem i can't reproduce momentarily. It seems to work on my machine.

**Closed** 2020-04-15 17:26 UTC
Labels: bug
